# Generated by Django 4.1.6 on 2023-05-01 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='Contact',
        ),
    ]
